spring:
  datasource:
    # Windows:
    #url: jdbc:oracle:thin:@magiceast_high?TNS_ADMIN=D:/Weas/Wallet_MagicEast
    # Linux:
    url: jdbc:oracle:thin:@magiceast_high?TNS_ADMIN=/home/ubuntu/Wallet_MagicEast
    username: ADMIN
    password: MagicEast123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080

app:
  # Windows:
  #upload-dir: D:/Weas/Antigravity repos/MagicEastBackEnd/uploads
  # Linux:
  upload-dir: /home/ubuntu/MagicEastBackEnd/uploads
jwt:
  secret: "5fbb2b44cb9c4f628eef2e545d09891f8af7cf0a463beb740fe0582b77e8d3c5290bfa93d7b9c72"
  expiration-ms: 3600000
